import requests
import smtplib
import os
import datetime
from email.mime.text import MIMEText
from email.header import Header

# --- 配置区域 ---
# 你想要关注的关键词
KEYWORDS = ["深圳", "人工智能", "财报", "华为", "新能源"]

# --- 1. 获取新闻 (示例：使用简单的 API 或 模拟数据) ---
def fetch_news_sources():
    """
    这里编写你的抓取逻辑。
    为了演示，这里模拟了两个来源：
    1. 一个假设的API
    2. 你之前使用的 cninfo 巨潮资讯逻辑
    """
    news_items = []
    
    # 来源 A: 模拟数据 (你可以替换为 RSS 解析或 requests 爬虫)
    print("正在获取通用新闻...")
    # 实际开发中可以使用 feedparser 解析 RSS，或者 requests 访问百度新闻/微博热搜
    mock_data = [
        {"title": "深圳发布最新人工智能扶持政策", "url": "http://example.com/1", "source": "本地新闻"},
        {"title": "某公司发布财报，净利润大增", "url": "http://example.com/2", "source": "财经网"},
        {"title": "今天天气不错", "url": "http://example.com/3", "source": "气象台"}, # 这个会被过滤掉
    ]
    news_items.extend(mock_data)

    # 来源 B: 你的巨潮资讯脚本 (移植版)
    print("正在获取公告信息...")
    try:
        url = 'http://www.cninfo.com.cn/new/hisAnnouncement/query'
        headers = {'User-Agent': 'Mozilla/5.0', 'X-Requested-With': 'XMLHttpRequest'}
        payload = {
            'stock': '', 'tabName': 'fulltext', 'pageSize': '10', 'pageNum': '1', 
            'column': 'szse', 'plate': 'sz', 'searchkey': '立讯精密', 'secid': '', 
            'sortName': '', 'sortType': '', 'isHLtitle': 'true'
        }
        # 注意：GitHub Actions IP 可能受限，实际使用可能需要代理或更稳健的重试机制
        r = requests.post(url, headers=headers, data=payload, timeout=10)
        if r.status_code == 200:
            anns = r.json().get('announcements') or []
            for a in anns:
                title = a['announcementTitle'].replace('<em>', '').replace('</em>', '')
                try:
                    ts = a.get('announcementTime')
                    # 检查是否是最近24小时的新闻
                    if ts: 
                        date_time = datetime.datetime.fromtimestamp(ts/1000)
                        if (datetime.datetime.now() - date_time).days < 1:
                            pass # 是最近的
                except:
                    pass
                
                link = 'http://static.cninfo.com.cn/' + a['adjunctUrl']
                news_items.append({"title": f"[公告] {title}", "url": link, "source": "巨潮资讯"})
    except Exception as e:
        print(f"巨潮资讯抓取失败: {e}")

    return news_items

# --- 2. 智能筛选 ---
def filter_news(items):
    """只保留包含关键词的新闻"""
    filtered = []
    for item in items:
        # 如果标题包含任意一个关键词
        if any(k in item['title'] for k in KEYWORDS):
            filtered.append(item)
    return filtered

# --- 3. 发送邮件 ---
def send_email(news_list):
    if not news_list:
        print("没有找到符合条件的新闻，不发送邮件。")
        return

    sender = os.environ.get("EMAIL_USER")
    password = os.environ.get("EMAIL_PASS") # 授权码，不是邮箱登录密码
    receiver = os.environ.get("EMAIL_TO")
    smtp_host = os.environ.get("EMAIL_HOST", "smtp.qq.com")
    smtp_port = int(os.environ.get("EMAIL_PORT", 465))

    if not all([sender, password, receiver]):
        print("错误：环境变量未配置 (EMAIL_USER, EMAIL_PASS, EMAIL_TO)")
        return

    # 生成 HTML 内容
    current_time = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")
    html_content = f"<h2>📅 每日新闻推送 ({current_time})</h2><ul>"
    
    for news in news_list:
        html_content += f"<li><b>[{news['source']}]</b> <a href='{news['url']}'>{news['title']}</a></li>"
    html_content += "</ul><p>Generated by GitHub Actions News Agent</p>"

    message = MIMEText(html_content, 'html', 'utf-8')
    message['From'] = Header(f"News Agent <{sender}>", 'utf-8')
    message['To'] = Header("我", 'utf-8')
    message['Subject'] = Header(f"今日资讯汇总 - {len(news_list)}条", 'utf-8')

    try:
        if smtp_port == 465:
            server = smtplib.SMTP_SSL(smtp_host, smtp_port)
        else:
            server = smtplib.SMTP(smtp_host, smtp_port)
            server.starttls()
            
        server.login(sender, password)
        server.sendmail(sender, [receiver], message.as_string())
        server.quit()
        print("✅ 邮件发送成功！")
    except Exception as e:
        print(f"❌ 邮件发送失败: {e}")

# --- 主程序 ---
if __name__ == "__main__":
    print("🤖 News Agent 启动...")
    all_news = fetch_news_sources()
    print(f"共获取到 {len(all_news)} 条原始数据")
    
    target_news = filter_news(all_news)
    print(f"筛选后剩余 {len(target_news)} 条关注数据")
    
    send_email(target_news)
